// GENERATED by tools/icons.py --emit — do not hand-edit.
// One semantic slot per row; all clients use the SAME lucide id.
import SwiftUI
import LucideSwift

/// Semantic icon slots shared by all Easy Agent clients.
///
/// `AppIcon` renders them with the bundled Lucide strokes (2pt, matching
/// the Flutter / Compose clients), so the same action shows the
/// same glyph on every platform.
public enum AppIcons {

    /// The `LucideIconName` for each slot (string lookup, e.g. a tool name).
    public static let table: [String: LucideIconName] = [
        "add": .plus,
        "apps": .layoutGrid,
        "arrow_up": .arrowUp,
        "asterisk": .asterisk,
        "attach": .paperclip,
        "audio": .audioLines,
        "back": .arrowLeft,
        "bell": .bell,
        "binary": .binary,
        "bolt": .zap,
        "book": .bookOpen,
        "bot": .bot,
        "box": .box,
        "braces": .braces,
        "branch": .gitBranch,
        "building": .building,
        "calendar": .calendar,
        "camera": .camera,
        "chat": .messageSquare,
        "chat_round": .messageCircle,
        "check": .check,
        "checked_square": .squareCheck,
        "checks": .checkCheck,
        "chevron_down": .chevronDown,
        "chevron_left": .chevronLeft,
        "chevron_right": .chevronRight,
        "chevron_select": .chevronsUpDown,
        "chevron_up": .chevronUp,
        "circle": .circle,
        "clipboard": .clipboardList,
        "clock": .clock,
        "close": .x,
        "cloud_down": .cloudDownload,
        "code": .code,
        "commit": .gitCommitHorizontal,
        "compass": .compass,
        "container": .container,
        "copy": .copy,
        "cpu": .cpu,
        "database": .database,
        "delete": .trash,
        "diff": .diff,
        "download": .download,
        "drive": .hardDrive,
        "edit": .pencil,
        "error": .circleAlert,
        "expand": .expand,
        "external": .externalLink,
        "eye": .eye,
        "eye_off": .eyeOff,
        "file": .fileText,
        "file_audio": .fileHeadphone,
        "file_code": .fileCode,
        "file_edit": .filePen,
        "file_image": .fileImage,
        "file_search": .fileSearch,
        "file_video": .filePlay,
        "film": .film,
        "filter": .funnel,
        "flask": .flaskConical,
        "folder": .folderOpen,
        "fork": .gitFork,
        "globe": .globe,
        "grip": .gripVertical,
        "hash": .hash,
        "history": .rotateCcwClock,
        "hourglass": .hourglass,
        "image": .image,
        "image_off": .imageOff,
        "image_plus": .imagePlus,
        "inbox": .inbox,
        "info": .info,
        "key": .key,
        "keyboard": .keyboard,
        "language": .languages,
        "layers": .layers,
        "link": .link,
        "list": .listChecks,
        "lock": .lock,
        "login": .logIn,
        "map": .mapPin,
        "maximize": .maximize,
        "merge": .gitMerge,
        "mic": .mic,
        "mic_vocal": .micVocal,
        "minimize": .minimize,
        "monitor": .monitor,
        "moon": .moon,
        "more": .ellipsis,
        "more_vertical": .ellipsisVertical,
        "music": .music,
        "network": .network,
        "notebook": .notebook,
        "palette": .palette,
        "pause": .pause,
        "pause_round": .circlePause,
        "pin": .pin,
        "pkg": .packageIcon,
        "play": .play,
        "play_round": .circlePlay,
        "plug": .plug,
        "printer": .printer,
        "puzzle": .puzzle,
        "refresh": .refreshCw,
        "revert": .rotateCcw,
        "rocket": .rocket,
        "route": .route,
        "save": .save,
        "scatter": .chartScatter,
        "search": .search,
        "send": .send,
        "server": .server,
        "settings": .settings,
        "shield": .shield,
        "shrink": .shrink,
        "sliders": .slidersHorizontal,
        "sparkles": .sparkles,
        "spinner": .loaderCircle,
        "star": .star,
        "stop": .square,
        "success": .circleCheckBig,
        "sun": .sun,
        "swap": .arrowLeftRight,
        "tag": .tag,
        "target": .circleDot,
        "terminal": .squareTerminal,
        "timer": .timer,
        "todo": .listTodo,
        "tools": .wrench,
        "undo": .undo2,
        "upload": .upload,
        "user": .user,
        "user_plus": .userRoundPlus,
        "users": .users,
        "video": .video,
        "warn": .triangleAlert,
    ]

    public static func named(_ slot: String) -> LucideIconName {
        table[slot] ?? .circle
    }

    public static let add: LucideIconName = .plus
    public static let apps: LucideIconName = .layoutGrid
    public static let arrow_up: LucideIconName = .arrowUp
    public static let asterisk: LucideIconName = .asterisk
    public static let attach: LucideIconName = .paperclip
    public static let audio: LucideIconName = .audioLines
    public static let back: LucideIconName = .arrowLeft
    public static let bell: LucideIconName = .bell
    public static let binary: LucideIconName = .binary
    public static let bolt: LucideIconName = .zap
    public static let book: LucideIconName = .bookOpen
    public static let bot: LucideIconName = .bot
    public static let box: LucideIconName = .box
    public static let braces: LucideIconName = .braces
    public static let branch: LucideIconName = .gitBranch
    public static let building: LucideIconName = .building
    public static let calendar: LucideIconName = .calendar
    public static let camera: LucideIconName = .camera
    public static let chat: LucideIconName = .messageSquare
    public static let chat_round: LucideIconName = .messageCircle
    public static let check: LucideIconName = .check
    public static let checked_square: LucideIconName = .squareCheck
    public static let checks: LucideIconName = .checkCheck
    public static let chevron_down: LucideIconName = .chevronDown
    public static let chevron_left: LucideIconName = .chevronLeft
    public static let chevron_right: LucideIconName = .chevronRight
    public static let chevron_select: LucideIconName = .chevronsUpDown
    public static let chevron_up: LucideIconName = .chevronUp
    public static let circle: LucideIconName = .circle
    public static let clipboard: LucideIconName = .clipboardList
    public static let clock: LucideIconName = .clock
    public static let close: LucideIconName = .x
    public static let cloud_down: LucideIconName = .cloudDownload
    public static let code: LucideIconName = .code
    public static let commit: LucideIconName = .gitCommitHorizontal
    public static let compass: LucideIconName = .compass
    public static let container: LucideIconName = .container
    public static let copy: LucideIconName = .copy
    public static let cpu: LucideIconName = .cpu
    public static let database: LucideIconName = .database
    public static let delete: LucideIconName = .trash
    public static let diff: LucideIconName = .diff
    public static let download: LucideIconName = .download
    public static let drive: LucideIconName = .hardDrive
    public static let edit: LucideIconName = .pencil
    public static let error: LucideIconName = .circleAlert
    public static let expand: LucideIconName = .expand
    public static let external: LucideIconName = .externalLink
    public static let eye: LucideIconName = .eye
    public static let eye_off: LucideIconName = .eyeOff
    public static let file: LucideIconName = .fileText
    public static let file_audio: LucideIconName = .fileHeadphone
    public static let file_code: LucideIconName = .fileCode
    public static let file_edit: LucideIconName = .filePen
    public static let file_image: LucideIconName = .fileImage
    public static let file_search: LucideIconName = .fileSearch
    public static let file_video: LucideIconName = .filePlay
    public static let film: LucideIconName = .film
    public static let filter: LucideIconName = .funnel
    public static let flask: LucideIconName = .flaskConical
    public static let folder: LucideIconName = .folderOpen
    public static let fork: LucideIconName = .gitFork
    public static let globe: LucideIconName = .globe
    public static let grip: LucideIconName = .gripVertical
    public static let hash: LucideIconName = .hash
    public static let history: LucideIconName = .rotateCcwClock
    public static let hourglass: LucideIconName = .hourglass
    public static let image: LucideIconName = .image
    public static let image_off: LucideIconName = .imageOff
    public static let image_plus: LucideIconName = .imagePlus
    public static let inbox: LucideIconName = .inbox
    public static let info: LucideIconName = .info
    public static let key: LucideIconName = .key
    public static let keyboard: LucideIconName = .keyboard
    public static let language: LucideIconName = .languages
    public static let layers: LucideIconName = .layers
    public static let link: LucideIconName = .link
    public static let list: LucideIconName = .listChecks
    public static let lock: LucideIconName = .lock
    public static let login: LucideIconName = .logIn
    public static let map: LucideIconName = .mapPin
    public static let maximize: LucideIconName = .maximize
    public static let merge: LucideIconName = .gitMerge
    public static let mic: LucideIconName = .mic
    public static let mic_vocal: LucideIconName = .micVocal
    public static let minimize: LucideIconName = .minimize
    public static let monitor: LucideIconName = .monitor
    public static let moon: LucideIconName = .moon
    public static let more: LucideIconName = .ellipsis
    public static let more_vertical: LucideIconName = .ellipsisVertical
    public static let music: LucideIconName = .music
    public static let network: LucideIconName = .network
    public static let notebook: LucideIconName = .notebook
    public static let palette: LucideIconName = .palette
    public static let pause: LucideIconName = .pause
    public static let pause_round: LucideIconName = .circlePause
    public static let pin: LucideIconName = .pin
    public static let pkg: LucideIconName = .packageIcon
    public static let play: LucideIconName = .play
    public static let play_round: LucideIconName = .circlePlay
    public static let plug: LucideIconName = .plug
    public static let printer: LucideIconName = .printer
    public static let puzzle: LucideIconName = .puzzle
    public static let refresh: LucideIconName = .refreshCw
    public static let revert: LucideIconName = .rotateCcw
    public static let rocket: LucideIconName = .rocket
    public static let route: LucideIconName = .route
    public static let save: LucideIconName = .save
    public static let scatter: LucideIconName = .chartScatter
    public static let search: LucideIconName = .search
    public static let send: LucideIconName = .send
    public static let server: LucideIconName = .server
    public static let settings: LucideIconName = .settings
    public static let shield: LucideIconName = .shield
    public static let shrink: LucideIconName = .shrink
    public static let sliders: LucideIconName = .slidersHorizontal
    public static let sparkles: LucideIconName = .sparkles
    public static let spinner: LucideIconName = .loaderCircle
    public static let star: LucideIconName = .star
    public static let stop: LucideIconName = .square
    public static let success: LucideIconName = .circleCheckBig
    public static let sun: LucideIconName = .sun
    public static let swap: LucideIconName = .arrowLeftRight
    public static let tag: LucideIconName = .tag
    public static let target: LucideIconName = .circleDot
    public static let terminal: LucideIconName = .squareTerminal
    public static let timer: LucideIconName = .timer
    public static let todo: LucideIconName = .listTodo
    public static let tools: LucideIconName = .wrench
    public static let undo: LucideIconName = .undo2
    public static let upload: LucideIconName = .upload
    public static let user: LucideIconName = .user
    public static let user_plus: LucideIconName = .userRoundPlus
    public static let users: LucideIconName = .users
    public static let video: LucideIconName = .video
    public static let warn: LucideIconName = .triangleAlert
}

/// Renders a Lucide slot, inheriting the colour (`.foregroundStyle`) the
/// way `Image(systemName:)` did.
public struct AppIcon: View {
    private let name: LucideIconName
    private let size: CGFloat?

    public init(_ name: LucideIconName, size: CGFloat? = nil) {
        self.name = name
        self.size = size
    }

    public var body: some View {
        LucideIcon(shape: name.shape, size: size ?? 16, strokeWidth: 2,
                   absoluteStrokeWidth: size != nil)
    }
}
