import CoreText
import SwiftUI
import AVFoundation

// Design tokens — port of the flutter opencode palette.

enum AppColors {
    struct Palette {
        let background: Color
        let foreground: Color
        let card: Color
        let popover: Color
        let primary: Color
        let onPrimary: Color
        let muted: Color
        let mutedForeground: Color
        let accent: Color
        let destructive: Color
        let border: Color
        let input: Color
        let success: Color
        let warning: Color
    }

    static let dark = Palette(
        background: Color(red: 0.04, green: 0.04, blue: 0.04),
        foreground: Color(red: 0.93, green: 0.93, blue: 0.93),
        card: Color(red: 0.08, green: 0.08, blue: 0.08),
        popover: Color(red: 0.12, green: 0.12, blue: 0.12),
        primary: Color(red: 0.98, green: 0.70, blue: 0.51),
        onPrimary: .black,
        muted: Color(red: 0.09, green: 0.09, blue: 0.09),
        mutedForeground: Color(red: 0.50, green: 0.50, blue: 0.50),
        accent: Color(red: 0.62, green: 0.49, blue: 0.85),
        destructive: Color(red: 0.88, green: 0.42, blue: 0.46),
        border: Color(red: 0.28, green: 0.28, blue: 0.28),
        input: Color(red: 0.24, green: 0.24, blue: 0.24),
        success: Color(red: 0.50, green: 0.85, blue: 0.56),
        warning: Color(red: 0.96, green: 0.65, blue: 0.26)
    )

    static let light = Palette(
        background: .white,
        foreground: Color(red: 0.10, green: 0.10, blue: 0.10),
        card: Color(red: 0.98, green: 0.98, blue: 0.98),
        popover: Color(red: 0.96, green: 0.96, blue: 0.96),
        primary: Color(red: 0.23, green: 0.49, blue: 0.85),
        onPrimary: .white,
        muted: Color(red: 0.95, green: 0.95, blue: 0.95),
        mutedForeground: Color(red: 0.54, green: 0.54, blue: 0.54),
        accent: Color(red: 0.84, green: 0.55, blue: 0.15),
        destructive: Color(red: 0.82, green: 0.22, blue: 0.24),
        border: Color(red: 0.72, green: 0.72, blue: 0.72),
        input: Color(red: 0.83, green: 0.83, blue: 0.83),
        success: Color(red: 0.24, green: 0.60, blue: 0.34),
        warning: Color(red: 0.84, green: 0.55, blue: 0.15)
    )

    static func palette(dark: Bool) -> Palette { dark ? AppColors.dark : AppColors.light }
}

enum AppSpacing {
    static let xs: CGFloat = 4
    static let sm: CGFloat = 8
    static let md: CGFloat = 12
    static let lg: CGFloat = 16
    static let xl: CGFloat = 24
}

enum AppLayout {
    static let compactBelow: CGFloat = 640
    static let wideThreshold: CGFloat = 1024
    static let railWidth: CGFloat = 96
}

/// Corner radii — mirrors flutter `AppRadius` (sm 6 / md 8 / lg 12).
enum AppRadius {
    static let sm: CGFloat = 6
    static let md: CGFloat = 8
    static let lg: CGFloat = 12
}

/// Type scale — mirrors flutter `AppTypography` (micro 10 / meta 12 / body 14)
/// plus the in-between sizes the reference uses. Every text in the app picks a
/// role from here so the four clients share one scale; `.appFont(.meta)` etc.
enum AppFont {
    case tiny, micro, meta, small, body, title, screenTitle

    var size: CGFloat {
        switch self {
        case .tiny: return 9
        case .micro: return 10
        case .meta: return 12
        case .small: return 13
        case .body: return 14
        case .title: return 16
        case .screenTitle: return 24
        }
    }

    var weight: Font.Weight {
        switch self {
        // The bundled family ships Regular(400) + SemiBold(600) only: every
        // heavier request maps to SemiBold so no engine synthesizes bold.
        case .title, .screenTitle: return .semibold
        default: return .regular
        }
    }
}

/// Bundled UI font names + one-time CoreText registration.
///
/// The same four files ship with the Flutter / WebUI / Compose clients
/// (generated by `tools/gen-fonts.py`), so `font(.custom(...))` here draws the
/// identical outlines. `Bundle.module` is the SwiftPM resource bundle the
/// `resources: [.process("Resources")]` target setting produces.
enum AppFonts {
    static let sans = "NotoSansSC"
    static let mono = "NotoSansMono"
    private static var registered = false

    static func registerBundled() {
        guard !registered else { return }
        registered = true
        for name in [
            "NotoSansSC-Regular", "NotoSansSC-SemiBold",
            "NotoSansMono-Regular", "NotoSansMono-SemiBold",
        ] {
            guard let url = Bundle.module.url(forResource: name, withExtension: "ttf") else {
                continue
            }
            CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
        }
    }
}

/// The palette carried down the view tree, mirroring Compose's
/// `LocalAppColors` / flutter's `ThemeExtension<AppColors>`. Screens read it
/// with `@Environment(\.appColors)` instead of recomputing
/// `AppColors.palette(dark: true)` — which is exactly the bug that made every
/// page after the login screen ignore the theme.
private struct AppColorsKey: EnvironmentKey {
    static let defaultValue = AppColors.light
}

extension EnvironmentValues {
    var appColors: AppColors.Palette {
        get { self[AppColorsKey.self] }
        set { self[AppColorsKey.self] = newValue }
    }
}

extension View {
    func appTheme(_ dark: Bool) -> some View {
        environment(\.colorScheme, dark ? .dark : .light)
            .environment(\.appColors, AppColors.palette(dark: dark))
    }

    /// Apply one of the shared type-scale roles.
    ///
    /// Uses the BUNDLED Noto Sans SC statics (see `AppFonts.registerBundled`)
    /// rather than the system face, so the four clients rasterize identical
    /// glyphs. `.weight(.semibold)` hits the real 600 face; `.weight(.bold)`
    /// is mapped to 600 by [AppFont.weight], since the family has no 700.
    func appFont(_ f: AppFont) -> some View {
        font(.custom(AppFonts.sans, size: f.size).weight(f.weight))
    }

    /// Monospaced variant (code/paths/diffs) at a given role's size.
    func appMonoFont(_ f: AppFont = .micro) -> some View {
        font(.custom(AppFonts.mono, size: f.size))
    }

    /// Standard form field chrome: muted fill, hairline outline, md radius —
    /// the same box `AppTextField`/`AppSelect` draw on the Compose side.
    func appFieldStyle(_ p: AppColors.Palette) -> some View {
        self
            .textFieldStyle(.plain)
            .padding(.horizontal, AppSpacing.md)
            .padding(.vertical, 11)
            .background(p.muted, in: RoundedRectangle(cornerRadius: AppRadius.md))
            .overlay(RoundedRectangle(cornerRadius: AppRadius.md).stroke(p.border.opacity(0.6)))
            .foregroundStyle(p.foreground)
    }
}

/// Uppercase section caption above a group of rows.
struct SectionLabel: View {
    @Environment(\.appColors) private var p
    let label: String
    init(_ label: String) { self.label = label }
    var body: some View {
        Text(label.uppercased())
            .appFont(.micro).fontWeight(.semibold)
            .foregroundStyle(p.mutedForeground)
    }
}

/// Labeled form field — caption above a styled box, the SwiftUI stand-in for
/// the Compose `AppTextField` and the flutter `inputDecorationTheme`.
struct AppField: View {
    @Environment(\.appColors) private var p
    let label: String?
    @Binding var text: String
    var secure = false
    var multiline = false
    var disabled = false
    var placeholder = ""

    init(_ label: String?, text: Binding<String>, secure: Bool = false, multiline: Bool = false, disabled: Bool = false, placeholder: String = "") {
        self.label = label
        self._text = text
        self.secure = secure
        self.multiline = multiline
        self.disabled = disabled
        self.placeholder = placeholder
    }

    var body: some View {
        VStack(alignment: .leading, spacing: AppSpacing.xs) {
            if let label {
                Text(label).appFont(.meta).foregroundStyle(p.mutedForeground)
            }
            Group {
                if secure {
                    SecureField(placeholder, text: $text)
                } else if multiline {
                    TextField(placeholder, text: $text, axis: .vertical).lineLimit(3...8)
                } else {
                    TextField(placeholder, text: $text)
                }
            }
            .appFieldStyle(p)
            .opacity(disabled ? 0.5 : 1)
            .disabled(disabled)
            .autocorrectionDisabled()
        }
    }
}

/// In-place select — same box as `AppField` with a chevron; the options open in
/// a menu (the platform-native analogue of the Compose `AppSelect` dropdown).
struct AppSelect: View {
    @Environment(\.appColors) private var p
    let label: String?
    @Binding var value: String
    var options: [(String, String)]
    var disabled = false

    init(_ label: String?, value: Binding<String>, options: [(String, String)], disabled: Bool = false) {
        self.label = label
        self._value = value
        self.options = options
        self.disabled = disabled
    }

    private var shown: String {
        options.first { $0.0 == value }?.1 ?? (value.isEmpty ? "—" : value)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: AppSpacing.xs) {
            if let label {
                Text(label).appFont(.meta).foregroundStyle(p.mutedForeground)
            }
            Menu {
                ForEach(options, id: \.0) { opt in
                    Button(opt.1.isEmpty ? opt.0 : opt.1) { value = opt.0 }
                }
            } label: {
                HStack(alignment: .top) {
                    Text(shown).appFont(.body).foregroundStyle(p.foreground)
                        .multilineTextAlignment(.leading)
                    Spacer()
                    AppIcon(AppIcons.chevron_down)
                        .appFont(.micro).foregroundStyle(p.mutedForeground)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
            .appFieldStyle(p)
            .opacity(disabled ? 0.5 : 1)
            .disabled(disabled)
        }
    }
}
